import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :phx_tools, PhxToolsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :appsignal, :config,
  active: true,
  ignore_actions: ["PhxToolsWeb.HealthController#index"],
  name: "phx.tools",
  otp_app: :phx_tools

config :logger, backends: [:console, {Appsignal.Logger.Backend, [group: "phoenix"]}]
